### ISSUE TITLE
firebase  Authentication

### ISSUE THREAD

**Issue by cdxgh** [cdxgh/Firebase_BookifyApp#1]
<img width="892" alt="Screenshot 2023-09-29 104332" src="https://github.com/cdxgh/Firebase_BookifyApp/assets/96329368/f86930e7-d296-40d9-98c6-2e4eea7b3c3f">

** Having this issue while I login with google using firbase Authentication in my this react app.**

https://github.com/cdxgh/Firebase_BookifyApp/assets/96329368/7a65aabd-99e4-4e46-b4af-221db2eb0498

**Comment by Ronixa584** [comment]
I can fix this issue. 
Please Assign it to me

**Comment by Abhiram1819** [comment]
Please assign me this issue.  I can fix it.

**Comment by cdxgh** [comment]
> I can fix this issue. Please Assign it to me

Start Working on this issue

**Comment by Ronixa584** [comment]
https://stackoverflow.com/questions/48076968/firebase-auth-unauthorized-domain-domain-is-not-authorized
I think its firebase issue

**Comment by cdxgh** [comment]
👍
